### ISSUE TITLE
$glyphicons-halflings-font-path missing from NPM version

### ISSUE THREAD

**Issue by WereDev** [inway/glyphicons-halflings#5]
Hello there,

I am in the process of upgrading from bower to npm on my projects and noticed that the glyphicons were breaking.  After investigating, it appears that the version of glyphicons that is published to NPM (https://www.npmjs.com/package/glyphicons-halflings) is missing the $glyphicons-halflings-font-path variable that you added.  Is there any way that you can update the version in NPM to also include this?

Thanks!

**Comment by SPodjasek** [comment]
You're right, it was added by #4 and I forgot to publish this to npm.

**Comment by WereDev** [comment]
Thank you! 🥇
